-- Seed data for items. Regenerated from data/seed.json — keep in sync.
insert into items (category, title, subtitle, emoji, source, image_url) values
  ('food', 'Neapolitan pizza', 'Blistered crust, San Marzano tomatoes, a fold-and-go classic.', '🍕', 'TasteAtlas 100 Best Dishes', null),
  ('food', 'Sushi night', 'Fresh nigiri and rolls for a light, celebratory dinner.', '🍣', 'TasteAtlas Best Dishes', null),
  ('food', 'Tacos al pastor', 'Spit-roasted pork, pineapple, and a squeeze of lime.', '🌮', 'TasteAtlas 100 Best Dishes', null),
  ('food', 'Tonkotsu ramen', 'Rich pork broth, springy noodles, cure for a cold night.', '🍜', 'TasteAtlas Best Dishes', null),
  ('food', 'Pad Thai', 'Sweet, tangy, and quick — the takeout everyone agrees on.', '🍜', 'TasteAtlas Best Cuisines', null),
  ('food', 'Butter chicken', 'Creamy tomato curry that wants extra naan on the side.', '🍛', 'TasteAtlas 100 Best Dishes', null),
  ('food', 'Smash burgers', 'Crispy-edged patties and melty cheese, no fuss.', '🍔', 'Popular Takeout Lists', null),
  ('food', 'Texas BBQ brisket', 'Low-and-slow smoke with a peppery bark, worth the drive.', '🍖', 'TasteAtlas 100 Best Dishes', null),
  ('food', 'Beef pho', 'Star-anise broth and rice noodles for a cozy slurp.', '🍜', 'TasteAtlas Best Dishes', null),
  ('food', 'Pork dumplings', 'Pan-fried or steamed, made for sharing off one plate.', '🥟', 'TasteAtlas Best Dishes', null),
  ('food', 'Korean fried chicken', 'Double-fried, glossy with gochujang glaze, dangerously crunchy.', '🍗', 'TasteAtlas 100 Best Dishes', null),
  ('food', 'Fish and chips', 'Beer-battered cod and vinegar-splashed fries, pub comfort.', '🍤', 'TasteAtlas Best Cuisines', null),
  ('food', 'Falafel wraps', 'Crispy chickpea fritters with tahini, an easy meatless win.', '🥙', 'TasteAtlas Best Dishes', null),
  ('food', 'Spaghetti carbonara', 'Egg, pecorino, and guanciale — Roman comfort in one pan.', '🍝', 'TasteAtlas 100 Best Dishes', null),
  ('food', 'Baked lasagna', 'Layered, bubbling, and better as leftovers tomorrow.', '🍝', 'TasteAtlas Best Cuisines', null),
  ('food', 'Burrito bowls', 'Build-your-own rice, beans, and toppings for picky pairs.', '🌯', 'Popular Takeout Lists', null),
  ('food', 'Poke bowls', 'Cubed raw fish over rice, fresh and endlessly customizable.', '🍤', 'TasteAtlas Best Dishes', null),
  ('food', 'Shakshuka brunch', 'Eggs poached in spiced tomato, scoop it up with bread.', '🥙', 'TasteAtlas 100 Best Dishes', null),
  ('food', 'Lamb gyros', 'Warm pita, seasoned meat, tzatziki dripping down your wrist.', '🥙', 'TasteAtlas 100 Best Dishes', null),
  ('food', 'Chicken tikka masala', 'Charred, saucy, and reliably crowd-pleasing.', '🍛', 'TasteAtlas 100 Best Dishes', null),
  ('food', 'Dim sum spread', 'A parade of little baskets and endless tea refills.', '🥟', 'TasteAtlas Best Cuisines', null),
  ('food', 'Bibimbap', 'Rice, veggies, egg, and gochujang mixed at the table.', '🍲', 'TasteAtlas 100 Best Dishes', null),
  ('food', 'Peking duck', 'Crackling skin wrapped in thin pancakes with scallion.', '🦆', 'TasteAtlas 100 Best Dishes', null),
  ('food', 'Seafood paella', 'Saffron rice with a golden crust, a weekend showpiece.', '🍤', 'TasteAtlas 100 Best Dishes', null),
  ('food', 'Croissants and coffee', 'Flaky, buttery, and best eaten warm from the bakery.', '🥐', 'TasteAtlas Best Cuisines', null),
  ('food', 'Chicken and waffles', 'Sweet-and-savory brunch with syrup and hot sauce.', '🍗', 'Popular Takeout Lists', null),
  ('food', 'Loaded nachos', 'A shareable mountain of chips, cheese, and jalapenos.', '🌯', 'Popular Takeout Lists', null),
  ('food', 'Chicken shawarma', 'Spit-roasted, garlicky, and stuffed into warm flatbread.', '🥙', 'TasteAtlas 100 Best Dishes', null),
  ('food', 'Buffalo wings', 'Spicy, saucy, and made for a game-night spread.', '🍗', 'Popular Takeout Lists', null),
  ('food', 'Mac and cheese', 'The ultimate creamy carb hug, baked till golden.', '🧀', 'Popular Takeout Lists', null),
  ('food', 'Ceviche', 'Citrus-cured fish, bright and refreshing on a hot day.', '🍤', 'TasteAtlas 100 Best Dishes', null),
  ('food', 'Beef empanadas', 'Flaky hand pies, perfect for grabbing on the go.', '🌯', 'TasteAtlas Best Dishes', null),
  ('food', 'Banh mi', 'Crackly baguette with pate, pickles, and cilantro.', '🥖', 'TasteAtlas 100 Best Dishes', null),
  ('food', 'Laksa', 'Coconut-curry noodle soup with a spicy, fragrant kick.', '🍜', 'TasteAtlas 100 Best Dishes', null),
  ('food', 'Chicken biryani', 'Fragrant layered rice with warm spices and tender meat.', '🍛', 'TasteAtlas 100 Best Dishes', null),
  ('food', 'Weekend pancakes', 'Fluffy stacks with butter and syrup, no rush required.', '🥐', 'Popular Takeout Lists', null),
  ('food', 'Steak frites', 'Seared steak and crisp fries, a bistro standby.', '🥩', 'TasteAtlas Best Cuisines', null),
  ('food', 'Gnocchi', 'Pillowy potato dumplings in butter, sage, or red sauce.', '🍝', 'TasteAtlas Best Cuisines', null),
  ('food', 'Enchiladas', 'Rolled tortillas smothered in sauce and melted cheese.', '🌯', 'TasteAtlas Best Cuisines', null),
  ('food', 'Thai green curry', 'Coconut-rich and herbaceous with a slow-building heat.', '🍛', 'TasteAtlas 100 Best Dishes', null),
  ('food', 'Pork bao buns', 'Soft steamed buns folded around sweet-savory filling.', '🥟', 'TasteAtlas Best Dishes', null),
  ('food', 'Gelato run', 'A scoop-and-stroll dessert stop on a warm evening.', '🍨', 'TasteAtlas Best Cuisines', null),
  ('food', 'Hot pot', 'Simmer your own broth at the table, dip and repeat.', '🍲', 'TasteAtlas Best Cuisines', null),
  ('food', 'Mezze platter', 'A grazing spread of hummus, olives, and warm pita.', '🥙', 'TasteAtlas Best Cuisines', null),
  ('food', 'Souvlaki plate', 'Grilled skewers with lemon, oregano, and a side of fries.', '🥙', 'TasteAtlas 100 Best Dishes', null),
  ('vacations', 'London, England', 'Museums, markets, and West End nights in a walkable capital.', '🏙️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'Paris, France', 'Cafe mornings, riverside strolls, and a skyline of icons.', '🏙️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'Rome, Italy', 'Ancient ruins and gelato on every cobblestone corner.', '🏙️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'Tokyo, Japan', 'Neon districts, quiet shrines, and unforgettable food.', '🏙️', 'Lonely Planet Best Destinations', null),
  ('vacations', 'Barcelona, Spain', 'Gaudi architecture, beach afternoons, and late tapas.', '🏙️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'Lisbon, Portugal', 'Pastel hills, tram rides, and seafood by the Atlantic.', '🏙️', 'Lonely Planet Best Destinations', null),
  ('vacations', 'Amsterdam, Netherlands', 'Canals, bikes, and world-class museums in a compact city.', '🏙️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'Bali, Indonesia', 'Rice terraces, temples, and beaches for slow days.', '🏝️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'Dubai, UAE', 'Skyscrapers, desert safaris, and glossy luxury.', '🏙️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'Sicily, Italy', 'Volcanoes, ruins, and some of Italy''s best street food.', '🏙️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'Kyoto, Japan', 'Golden temples, bamboo groves, and geisha districts.', '🏙️', 'Lonely Planet Best Destinations', null),
  ('vacations', 'Osaka, Japan', 'A food-lover''s playground with buzzing night streets.', '🏙️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'Marrakech, Morocco', 'Labyrinth souks, rooftop mint tea, and desert edges.', '🏙️', 'Lonely Planet Best Destinations', null),
  ('vacations', 'Istanbul, Turkey', 'Where continents meet over bazaars and grand mosques.', '🏙️', 'Lonely Planet Best Destinations', null),
  ('vacations', 'Santorini, Greece', 'Whitewashed cliffs and sunsets over a caldera.', '🏝️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'Prague, Czech Republic', 'Fairy-tale spires, cozy pubs, and a storied old town.', '🏙️', 'Lonely Planet Best Destinations', null),
  ('vacations', 'Vienna, Austria', 'Grand palaces, coffeehouse culture, and classical music.', '🏙️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'Reykjavik, Iceland', 'Base camp for waterfalls, geysers, and northern lights.', '🏙️', 'Lonely Planet Best Destinations', null),
  ('vacations', 'Queenstown, New Zealand', 'Alpine lakes and adventure sports at every turn.', '🏔️', 'Lonely Planet Best Destinations', null),
  ('vacations', 'Cape Town, South Africa', 'Table Mountain, penguin beaches, and nearby wine country.', '🏝️', 'Lonely Planet Best Destinations', null),
  ('vacations', 'Buenos Aires, Argentina', 'Tango nights, steak dinners, and grand old boulevards.', '🏙️', 'Lonely Planet Best Destinations', null),
  ('vacations', 'Rio de Janeiro, Brazil', 'Beaches, samba, and a mountain-framed skyline.', '🏝️', 'Lonely Planet Best Destinations', null),
  ('vacations', 'Bangkok, Thailand', 'Street food, gilded temples, and buzzing night markets.', '🏙️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'Hanoi, Vietnam', 'Old-quarter chaos, lakeside calm, and endless pho.', '🏙️', 'Lonely Planet Best Destinations', null),
  ('vacations', 'Machu Picchu, Peru', 'A misty Inca citadel reached through the Andes.', '🏔️', 'Lonely Planet Best Destinations', null),
  ('vacations', 'Banff, Canada', 'Turquoise lakes and jagged peaks in the Rockies.', '🏔️', 'Lonely Planet Best Destinations', null),
  ('vacations', 'Mexico City, Mexico', 'Murals, markets, and one of the world''s great food scenes.', '🏙️', 'Lonely Planet Best Destinations', null),
  ('vacations', 'Tulum, Mexico', 'Jungle cenotes and Caribbean beaches beside Mayan ruins.', '🏝️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'New York City, USA', 'Nonstop energy, iconic sights, and every cuisine at once.', '🏙️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'New Orleans, Louisiana', 'Jazz, beignets, and French Quarter revelry.', '🏙️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'Charleston, South Carolina', 'Cobblestone charm, Southern cooking, and coastal breeze.', '🏙️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'Savannah, Georgia', 'Oak-shaded squares and a walkable historic heart.', '🏙️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'San Francisco, California', 'Foggy hills, the Golden Gate, and eclectic neighborhoods.', '🏙️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'Maui, Hawaii', 'Volcanic sunrises, waterfalls, and easy beach days.', '🏝️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'Sedona, Arizona', 'Red-rock canyons and desert trails at golden hour.', '🏔️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'Grand Canyon, Arizona', 'A mile-deep gorge that swallows the horizon.', '🏔️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'Yellowstone, Wyoming', 'Geysers, bison, and wild backcountry in America''s first park.', '🏔️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'Yosemite, California', 'Granite giants, waterfalls, and giant sequoias.', '🏔️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'Aspen, Colorado', 'Powder slopes in winter, wildflower hikes in summer.', '🏔️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'Key West, Florida', 'End-of-the-road island vibes and technicolor sunsets.', '🏝️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'Nashville, Tennessee', 'Honky-tonks, hot chicken, and live music nightly.', '🏙️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'Asheville, North Carolina', 'Mountain breweries, art galleries, and Blue Ridge views.', '🏙️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'San Diego, California', 'Easygoing beaches, tacos, and near-perfect weather.', '🏝️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'Portland, Oregon', 'Food carts, coffee, and forests a short drive away.', '🏙️', 'Tripadvisor Travelers'' Choice', null),
  ('vacations', 'Glacier National Park, Montana', 'Alpine lakes and a jaw-dropping road over the peaks.', '🏔️', 'Tripadvisor Travelers'' Choice', null),
  ('activities', 'Sunrise hike', 'Beat the crowds to a summit view and morning quiet.', '🥾', 'Couples Activity Lists', null),
  ('activities', 'Board game night', 'Snacks, a stack of games, and friendly rivalry.', '🎲', 'Couples Activity Lists', null),
  ('activities', 'Cooking class', 'Learn a new dish together and eat your homework.', '🍳', 'Couples Activity Lists', null),
  ('activities', 'Escape room', 'Race the clock and test how well you two team up.', '🔐', 'Couples Activity Lists', null),
  ('activities', 'Pottery class', 'Get your hands messy shaping something wobbly and yours.', '🎨', 'Couples Activity Lists', null),
  ('activities', 'Rock climbing gym', 'Belay each other up the wall for a low-key thrill.', '🧗', 'Couples Activity Lists', null),
  ('activities', 'Kayaking', 'Paddle a calm lake or river at your own pace.', '🛶', 'Couples Activity Lists', null),
  ('activities', 'Farmers market morning', 'Wander the stalls and cook with what you find.', '🧺', 'Couples Activity Lists', null),
  ('activities', 'Bike ride', 'An easy loop through the park or along the water.', '🚴', 'Couples Activity Lists', null),
  ('activities', 'Mini golf', 'Windmills, tiny bridges, and bragging rights on the line.', '⛳', 'Couples Activity Lists', null),
  ('activities', 'Bowling', 'Rent the shoes, split the lane, keep it silly.', '🎳', 'Couples Activity Lists', null),
  ('activities', 'Paint and sip', 'Follow along to a canvas with a glass in hand.', '🎨', 'Couples Activity Lists', null),
  ('activities', 'Camping trip', 'Tent, campfire, and a night under real stars.', '🏕️', 'Couples Activity Lists', null),
  ('activities', 'Weekend road trip', 'Pick a direction, make a playlist, and just drive.', '🚗', 'Couples Activity Lists', null),
  ('activities', 'Museum afternoon', 'Wander galleries and debate your favorites over coffee.', '🖼️', 'Couples Activity Lists', null),
  ('activities', 'Botanical garden stroll', 'A slow, green walk with plenty to point at.', '🌷', 'Couples Activity Lists', null),
  ('activities', 'Bouldering', 'Short problem-solving climbs, no ropes required.', '🧗', 'Couples Activity Lists', null),
  ('activities', 'Ice skating', 'Wobble around the rink and catch each other laughing.', '⛸️', 'Couples Activity Lists', null),
  ('activities', 'Yoga class', 'Stretch it out together and leave a little calmer.', '🧘', 'Couples Activity Lists', null),
  ('activities', 'Thrift store hunt', 'Dig for treasure and dare each other into weird outfits.', '👕', 'Couples Activity Lists', null),
  ('activities', 'Beach day', 'Towels, waves, and absolutely nowhere to be.', '🏖️', 'Couples Activity Lists', null),
  ('activities', 'Apple picking', 'Fill a basket at the orchard, then bake something.', '🍎', 'Couples Activity Lists', null),
  ('activities', 'Trampoline park', 'Bounce until your legs give out, guaranteed giggles.', '🤸', 'Couples Activity Lists', null),
  ('activities', 'Go-kart racing', 'Full-throttle laps and a photo finish.', '🏎️', 'Couples Activity Lists', null),
  ('activities', 'Axe throwing', 'Surprisingly satisfying, oddly competitive.', '🛶', 'Couples Activity Lists', null),
  ('activities', 'City scavenger hunt', 'A checklist, a timer, and your own downtown.', '🧭', 'Couples Activity Lists', null),
  ('activities', 'Volunteer together', 'Give a few hours to a cause you both care about.', '🤝', 'Couples Activity Lists', null),
  ('activities', 'Home workout challenge', 'Push through a sweaty circuit side by side.', '🧘', 'Couples Activity Lists', null),
  ('activities', 'Photo walk', 'Wander with a camera and hunt for good light.', '📷', 'Couples Activity Lists', null),
  ('activities', 'Stand-up paddleboarding', 'Balance on calm water and try not to fall in.', '🛶', 'Couples Activity Lists', null),
  ('activities', 'Fishing trip', 'Cast a line, wait, and enjoy the quiet.', '🎣', 'Couples Activity Lists', null),
  ('activities', 'Aquarium visit', 'Drift past glowing tanks and giant tanks of sharks.', '🐠', 'Couples Activity Lists', null),
  ('activities', 'Zoo day', 'Stroll the exhibits and pick your spirit animals.', '🦁', 'Couples Activity Lists', null),
  ('activities', 'Indoor skydiving', 'Float in a wind tunnel for a rush without the plane.', '🪂', 'Couples Activity Lists', null),
  ('activities', 'Batting cages', 'Take swings and settle who''s got the better arm.', '🏎️', 'Couples Activity Lists', null),
  ('activities', 'Disc golf', 'A relaxed walk-and-throw around a wooded course.', '⛳', 'Couples Activity Lists', null),
  ('activities', 'Rollerblading', 'Cruise a smooth path and pretend it''s the nineties.', '🛼', 'Couples Activity Lists', null),
  ('activities', 'Snorkeling', 'Float over reefs and spot fish in clear shallows.', '🏖️', 'Couples Activity Lists', null),
  ('activities', 'Ski day', 'Carve some runs and warm up over lodge cocoa.', '⛸️', 'Couples Activity Lists', null),
  ('activities', 'Horseback riding', 'A gentle trail ride through open country.', '🐴', 'Couples Activity Lists', null),
  ('activities', 'Geocaching', 'Follow GPS coordinates to hidden little caches.', '🧭', 'Couples Activity Lists', null),
  ('activities', 'Puzzle marathon', 'Spread out a thousand pieces and lose the afternoon.', '🎲', 'Couples Activity Lists', null),
  ('activities', 'Plant a garden', 'Dig in the dirt and grow something together.', '🌷', 'Couples Activity Lists', null),
  ('activities', 'Brewery tour', 'Sample local pours and learn how it''s made.', '🍺', 'Couples Activity Lists', null),
  ('activities', 'Dance class', 'Learn a few steps and step on a few toes.', '💃', 'Couples Activity Lists', null),
  ('date_nights', 'Sunset picnic', 'Blanket, snacks, and golden-hour light on your faces.', '🧺', 'Date Night Idea Lists', null),
  ('date_nights', 'Stargazing', 'Drive somewhere dark and find constellations together.', '🌅', 'Date Night Idea Lists', null),
  ('date_nights', 'Wine tasting', 'Swirl, sip, and pretend you can tell the notes apart.', '🍷', 'Date Night Idea Lists', null),
  ('date_nights', 'Karaoke night', 'Belt a duet badly and love every second of it.', '🎤', 'Date Night Idea Lists', null),
  ('date_nights', 'Movie marathon at home', 'Pajamas, popcorn, and a trilogy you never finished.', '🎬', 'Date Night Idea Lists', null),
  ('date_nights', 'Candlelit dinner', 'Dress up a little and linger over a slow meal.', '🍽️', 'Date Night Idea Lists', null),
  ('date_nights', 'Live music show', 'Catch a local band and dance where you''re standing.', '🎶', 'Date Night Idea Lists', null),
  ('date_nights', 'Comedy club', 'Laugh in the dark and hope you don''t get heckled.', '🤣', 'Date Night Idea Lists', null),
  ('date_nights', 'Drive-in movie', 'Back seat, blankets, and a double feature under the stars.', '🎬', 'Date Night Idea Lists', null),
  ('date_nights', 'Rooftop bar', 'A cocktail with a skyline view as the sun drops.', '🍸', 'Date Night Idea Lists', null),
  ('date_nights', 'Cook a new recipe', 'Tackle something ambitious and clean up together.', '🍳', 'Date Night Idea Lists', null),
  ('date_nights', 'Home spa night', 'Face masks, candles, and zero reason to leave the couch.', '💆', 'Date Night Idea Lists', null),
  ('date_nights', 'Sunset beach walk', 'Bare feet, cool sand, and the sky doing its best work.', '🏖️', 'Date Night Idea Lists', null),
  ('date_nights', 'Ice cream date', 'A cone, a slow stroll, and a stolen bite of theirs.', '🍦', 'Date Night Idea Lists', null),
  ('date_nights', 'Bookstore browse', 'Wander the aisles and pick a read for each other.', '📖', 'Date Night Idea Lists', null),
  ('date_nights', 'Coffee shop date', 'Two drinks, a corner table, and a long conversation.', '☕', 'Date Night Idea Lists', null),
  ('date_nights', 'Game night for two', 'Cards or a two-player board game with real stakes.', '🕹️', 'Date Night Idea Lists', null),
  ('date_nights', 'Blanket fort', 'Build a cozy fort and watch movies inside it.', '🔥', 'Date Night Idea Lists', null),
  ('date_nights', 'Couples massage', 'Book a side-by-side treatment and fully unwind.', '💆', 'Date Night Idea Lists', null),
  ('date_nights', 'Dinner and a play', 'A nice meal followed by a night at the theater.', '🍽️', 'Date Night Idea Lists', null),
  ('date_nights', 'Arcade night', 'Trade tokens for tickets and a plastic prize.', '🕹️', 'Date Night Idea Lists', null),
  ('date_nights', 'Night market food crawl', 'Split small bites from stall to glowing stall.', '🍢', 'Date Night Idea Lists', null),
  ('date_nights', 'Sunrise coffee', 'Wake early, grab drinks, and watch the day start.', '🌅', 'Date Night Idea Lists', null),
  ('date_nights', 'Paint night at home', 'Two canvases, one bottle, and questionable art.', '💕', 'Date Night Idea Lists', null),
  ('date_nights', 'Fondue night', 'Dip bread and fruit into a warm pot of cheese or chocolate.', '🍷', 'Date Night Idea Lists', null),
  ('date_nights', 'Jazz bar', 'Low light, a smooth set, and drinks in hand.', '🍷', 'Date Night Idea Lists', null),
  ('date_nights', 'Dancing out', 'Hit a floor and move until your feet complain.', '🎶', 'Date Night Idea Lists', null),
  ('date_nights', 'Trivia night', 'Team up at the bar and defend your useless knowledge.', '🕹️', 'Date Night Idea Lists', null),
  ('date_nights', 'Breakfast for dinner', 'Pancakes and eggs at night, because the rules are fake.', '🍽️', 'Date Night Idea Lists', null),
  ('date_nights', 'Watch the sunrise', 'Set an early alarm and greet the day together.', '🌅', 'Date Night Idea Lists', null),
  ('date_nights', 'Late-night diner run', 'Milkshakes and fries in a booth at midnight.', '💕', 'Date Night Idea Lists', null),
  ('date_nights', 'Cocktails at home', 'Shake up two new drinks and rate each other''s.', '🍷', 'Date Night Idea Lists', null),
  ('date_nights', 'Themed dinner night', 'Pick a country and cook, dress, and eat the part.', '🍽️', 'Date Night Idea Lists', null),
  ('date_nights', 'Puzzle and wine night', 'A quiet jigsaw, good music, and a glass each.', '🍷', 'Date Night Idea Lists', null),
  ('date_nights', 'Ferris wheel ride', 'A slow loop up for a view and a nervous laugh.', '🎡', 'Date Night Idea Lists', null),
  ('date_nights', 'Ghost tour', 'A spooky guided walk through the old part of town.', '👻', 'Date Night Idea Lists', null),
  ('date_nights', 'Fireplace evening', 'Warm drinks, low light, and nowhere else to be.', '🔥', 'Date Night Idea Lists', null),
  ('date_nights', 'Food festival', 'Graze your way through a street full of vendors.', '🍢', 'Date Night Idea Lists', null),
  ('date_nights', 'Rent a rowboat', 'Paddle around the pond and let someone else steer.', '🚣', 'Date Night Idea Lists', null),
  ('date_nights', 'Sunset drive', 'Roll the windows down and chase the horizon.', '💕', 'Date Night Idea Lists', null),
  ('date_nights', 'Bake together', 'Flour everywhere, cookies at the end, worth it.', '🍳', 'Date Night Idea Lists', null),
  ('date_nights', 'Photo booth date', 'Cram in for four goofy frames to keep forever.', '🕹️', 'Date Night Idea Lists', null),
  ('date_nights', 'At-home pedicures', 'Foot soak, polish, and a movie playing in the back.', '💆', 'Date Night Idea Lists', null),
  ('date_nights', 'Slow dance in the kitchen', 'One song, no audience, just the two of you.', '🎶', 'Date Night Idea Lists', null),
  ('date_nights', 'Write letters to each other', 'Trade handwritten notes to open and keep.', '📖', 'Date Night Idea Lists', null),
  ('shows', 'Breaking Bad', 'A chemistry teacher''s slow slide into a meth kingpin.', '📺', 'IMDb Top 250', null),
  ('shows', 'The Sopranos', 'A mob boss juggles the family and the Family in therapy.', '📺', 'IMDb Top 250', null),
  ('shows', 'The Wire', 'Baltimore''s streets and institutions seen from all sides.', '📺', 'IMDb Top 250', null),
  ('shows', 'Game of Thrones', 'Warring houses scheme for a throne as winter looms.', '📺', 'IMDb Top 250', null),
  ('shows', 'Stranger Things', 'Kids, a monster, and eighties nostalgia in a small town.', '📺', 'Rotten Tomatoes Popular', null),
  ('shows', 'The Office', 'Mockumentary chaos at a very ordinary paper company.', '📺', 'IMDb Top 250', null),
  ('shows', 'Friends', 'Six pals, one couch, and a decade of New York hangouts.', '📺', 'IMDb Top 250', null),
  ('shows', 'The Last of Us', 'A hardened survivor escorts a girl across a broken country.', '📺', 'Rotten Tomatoes Popular', null),
  ('shows', 'Succession', 'A media dynasty tears itself apart over who''s next.', '📺', 'Rotten Tomatoes Popular', null),
  ('shows', 'Ted Lasso', 'An upbeat coach wins over English football with kindness.', '📺', 'Rotten Tomatoes Popular', null),
  ('shows', 'The Bear', 'A fine-dining chef fights to save a chaotic sandwich shop.', '📺', 'Rotten Tomatoes Popular', null),
  ('shows', 'Severance', 'Office workers split their memories between work and home.', '📺', 'Rotten Tomatoes Popular', null),
  ('shows', 'Better Call Saul', 'How a small-time lawyer becomes a slippery legend.', '📺', 'IMDb Top 250', null),
  ('shows', 'Chernobyl', 'The 1986 nuclear disaster and the people who faced it.', '📺', 'IMDb Top 250', null),
  ('shows', 'Fleabag', 'A sharp, funny woman narrates her messy life to you.', '📺', 'Rotten Tomatoes Popular', null),
  ('shows', 'The Crown', 'Decades of royal duty, scandal, and family behind palace walls.', '📺', 'Rotten Tomatoes Popular', null),
  ('shows', 'Wednesday', 'A deadpan Addams teen solves mysteries at a strange school.', '📺', 'Rotten Tomatoes Popular', null),
  ('shows', 'The Mandalorian', 'A lone bounty hunter and a tiny green ward roam the galaxy.', '📺', 'Rotten Tomatoes Popular', null),
  ('shows', 'House of the Dragon', 'A civil war splits the dragon-riding Targaryens.', '📺', 'Rotten Tomatoes Popular', null),
  ('shows', 'Shogun', 'A stranded English sailor navigates feudal Japanese politics.', '📺', 'Rotten Tomatoes Popular', null),
  ('shows', 'True Detective', 'Two detectives, one haunting case, told across time.', '📺', 'IMDb Top 250', null),
  ('shows', 'Peaky Blinders', 'A ruthless Birmingham gang claws its way up post-war England.', '📺', 'Rotten Tomatoes Popular', null),
  ('shows', 'Dark', 'A missing child unravels time travel across a German town.', '📺', 'IMDb Top 250', null),
  ('shows', 'Squid Game', 'Desperate players risk everything in deadly kids'' games.', '📺', 'Rotten Tomatoes Popular', null),
  ('shows', 'Only Murders in the Building', 'Three neighbors podcast their way through a real murder.', '📺', 'Rotten Tomatoes Popular', null),
  ('shows', 'Silo', 'Thousands live underground, forbidden to ask why.', '📺', 'Rotten Tomatoes Popular', null),
  ('shows', 'The Godfather', 'A reluctant son inherits his family''s crime empire.', '🎬', 'IMDb Top 250', null),
  ('shows', 'The Shawshank Redemption', 'A wrongly jailed banker quietly plots his freedom.', '🎬', 'IMDb Top 250', null),
  ('shows', 'Pulp Fiction', 'Interwoven L.A. crime stories told wildly out of order.', '🎬', 'IMDb Top 250', null),
  ('shows', 'Inception', 'A thief steals secrets by diving into people''s dreams.', '🎬', 'IMDb Top 250', null),
  ('shows', 'The Dark Knight', 'Batman faces a city-shaking agent of chaos in the Joker.', '🎬', 'IMDb Top 250', null),
  ('shows', 'Parasite', 'A poor family cons its way into a wealthy household.', '🎬', 'IMDb Top 250', null),
  ('shows', 'Everything Everywhere All at Once', 'A weary mom saves the multiverse mid-tax-audit.', '🎬', 'IMDb Top 250', null),
  ('shows', 'Interstellar', 'Explorers chase humanity''s future through a wormhole.', '🎬', 'IMDb Top 250', null),
  ('shows', 'Spirited Away', 'A girl works in a spirit bathhouse to free her parents.', '🎬', 'IMDb Top 250', null),
  ('shows', 'Oppenheimer', 'The tense story of the man behind the atomic bomb.', '🎬', 'Rotten Tomatoes Popular', null),
  ('shows', 'Barbie', 'A doll''s existential road trip out of a perfect plastic world.', '🎬', 'Rotten Tomatoes Popular', null),
  ('shows', 'Dune: Part Two', 'A desert prophecy, a rebellion, and revenge on a spice planet.', '🎬', 'Rotten Tomatoes Popular', null),
  ('shows', 'La La Land', 'A jazz pianist and an actress chase dreams and each other.', '🎬', 'IMDb Top 250', null),
  ('shows', 'Get Out', 'A meet-the-parents weekend curdles into pure horror.', '🎬', 'Rotten Tomatoes Popular', null),
  ('shows', 'Whiplash', 'A drummer and a brutal mentor push each other to the edge.', '🎬', 'IMDb Top 250', null),
  ('shows', 'The Grand Budapest Hotel', 'A concierge and a bellhop caper through a pastel Europe.', '🎬', 'IMDb Top 250', null),
  ('shows', 'Spider-Man: Into the Spider-Verse', 'A teen meets his multiverse in a comic-book-come-alive.', '🎬', 'IMDb Top 250', null),
  ('shows', 'Knives Out', 'A gentleman detective untangles a very rich family''s lies.', '🎬', 'Rotten Tomatoes Popular', null),
  ('shows', 'Past Lives', 'Two childhood friends reunite decades and continents later.', '🎬', 'Rotten Tomatoes Popular', null);
