/**
 * Suggestion list for the "Add a city" field. NOT a validation allowlist —
 * anywhere Google Places and Foursquare serve is a legitimate location, so a
 * city missing from here must still be typeable by hand.
 *
 * Every entry is in the canonical `City, Region` form that normalizeLocation
 * produces and that hasRegion demands, so a picked suggestion is guaranteed to
 * pass both and to land in the same Places cache bucket as the same city typed
 * by hand. cities.test.ts asserts that for the whole list, entry by entry —
 * that is what makes "the cities get populated correctly" checked rather than
 * hoped. Keep it that way when adding: run the tests, do not eyeball it.
 *
 * Bundled deliberately rather than fetched: CLAUDE.md forbids the frontend
 * calling third-party APIs at runtime, Places Autocomplete bills per session
 * (which is what this whole item exists to stop), and a bundled list works in
 * offline demo mode.
 *
 * Drafting this list is what caught the casing defect fixed alongside it: the
 * 1-2 character uppercase rule that keeps `wa` as `WA` was applied to every
 * part, so `El Paso` canonicalized to `EL Paso` and `Ho Chi Minh City` to
 * `HO Chi Minh City`. Storing those spellings here would have made the list
 * agree with the bug and put them in front of users. The rule now applies per
 * comma part, so these entries are both correct AND canonical — which is the
 * only combination the test above accepts.
 */
export const CITY_SUGGESTIONS: readonly string[] = [
  // US — the top metros, roughly by population
  'New York, NY',
  'Los Angeles, CA',
  'Chicago, IL',
  'Houston, TX',
  'Phoenix, AZ',
  'Philadelphia, PA',
  'San Antonio, TX',
  'San Diego, CA',
  'Dallas, TX',
  'Austin, TX',
  'Jacksonville, FL',
  'Fort Worth, TX',
  'San Jose, CA',
  'Columbus, OH',
  'Charlotte, NC',
  'Indianapolis, IN',
  'San Francisco, CA',
  'Seattle, WA',
  'Denver, CO',
  'Oklahoma City, OK',
  'Nashville, TN',
  'Washington, DC',
  'El Paso, TX',
  'Las Vegas, NV',
  'Boston, MA',
  'Detroit, MI',
  'Portland, OR',
  'Louisville, KY',
  'Memphis, TN',
  'Baltimore, MD',
  'Milwaukee, WI',
  'Albuquerque, NM',
  'Tucson, AZ',
  'Fresno, CA',
  'Sacramento, CA',
  'Mesa, AZ',
  'Atlanta, GA',
  'Kansas City, MO',
  'Colorado Springs, CO',
  'Raleigh, NC',
  'Omaha, NE',
  'Miami, FL',
  'Long Beach, CA',
  'Virginia Beach, VA',
  'Oakland, CA',
  'Minneapolis, MN',
  'Tampa, FL',
  'Tulsa, OK',
  'Arlington, TX',
  'New Orleans, LA',
  'Wichita, KS',
  'Cleveland, OH',
  'Bakersfield, CA',
  'Aurora, CO',
  'Anaheim, CA',
  'Honolulu, HI',
  'Santa Ana, CA',
  'Riverside, CA',
  'Corpus Christi, TX',
  'Lexington, KY',
  'Henderson, NV',
  'Stockton, CA',
  'St. Paul, MN',
  'Cincinnati, OH',
  'Pittsburgh, PA',
  'Greensboro, NC',
  'Anchorage, AK',
  'Plano, TX',
  'Lincoln, NE',
  'Orlando, FL',
  'Irvine, CA',
  'Newark, NJ',
  'Toledo, OH',
  'Durham, NC',
  'Chula Vista, CA',
  'Fort Wayne, IN',
  'Jersey City, NJ',
  'St. Petersburg, FL',
  'Laredo, TX',
  'Madison, WI',
  'Chandler, AZ',
  'Buffalo, NY',
  'Lubbock, TX',
  'Scottsdale, AZ',
  'Reno, NV',
  'Glendale, AZ',
  'Gilbert, AZ',
  'Winston-Salem, NC',
  'North Las Vegas, NV',
  'Norfolk, VA',
  'Chesapeake, VA',
  'Garland, TX',
  'Irving, TX',
  'Hialeah, FL',
  'Fremont, CA',
  'Boise, ID',
  'Richmond, VA',
  'Baton Rouge, LA',
  'Spokane, WA',
  'Des Moines, IA',
  'Tacoma, WA',
  'San Bernardino, CA',
  'Modesto, CA',
  'Fontana, CA',
  'Santa Clarita, CA',
  'Birmingham, AL',
  'Oxnard, CA',
  'Fayetteville, NC',
  'Moreno Valley, CA',
  'Rochester, NY',
  'Glendale, CA',
  'Huntington Beach, CA',
  'Salt Lake City, UT',
  'Grand Rapids, MI',
  'Amarillo, TX',
  'Yonkers, NY',
  'Aurora, IL',
  'Montgomery, AL',
  'Akron, OH',
  'Little Rock, AR',
  'Huntsville, AL',
  'Augusta, GA',
  'Port St. Lucie, FL',
  'Grand Prairie, TX',
  'Columbus, GA',
  'Tallahassee, FL',
  'Overland Park, KS',
  'Tempe, AZ',
  'McKinney, TX',
  'Mobile, AL',
  'Cape Coral, FL',
  'Shreveport, LA',
  'Frisco, TX',
  'Knoxville, TN',
  'Worcester, MA',
  'Brownsville, TX',
  'Vancouver, WA',
  'Fort Lauderdale, FL',
  'Sioux Falls, SD',
  'Ontario, CA',
  'Chattanooga, TN',
  'Providence, RI',
  'Newport News, VA',
  'Rancho Cucamonga, CA',
  'Santa Rosa, CA',
  'Oceanside, CA',
  'Salem, OR',
  'Elk Grove, CA',
  'Garden Grove, CA',
  'Pembroke Pines, FL',
  'Peoria, AZ',
  'Eugene, OR',
  'Corona, CA',
  'Cary, NC',
  'Springfield, MO',
  'Fort Collins, CO',
  'Jackson, MS',
  'Alexandria, VA',
  'Hayward, CA',
  'Lancaster, CA',
  'Lakewood, CO',
  'Clarksville, TN',
  'Palmdale, CA',
  'Salinas, CA',
  'Springfield, MA',
  'Hollywood, FL',
  'Pasadena, TX',
  'Sunnyvale, CA',
  'Macon, GA',
  'Kansas City, KS',
  'Pomona, CA',
  'Escondido, CA',
  'Killeen, TX',
  'Naperville, IL',
  'Joliet, IL',
  'Bellevue, WA',
  'Rockford, IL',
  'Savannah, GA',
  'Paterson, NJ',
  'Torrance, CA',
  'Bridgeport, CT',
  'McAllen, TX',
  'Mesquite, TX',
  'Syracuse, NY',
  'Midland, TX',
  'Pasadena, CA',
  'Murfreesboro, TN',
  'Miramar, FL',
  'Dayton, OH',
  'Fullerton, CA',
  'Orange, CA',
  'West Valley City, UT',
  'Olathe, KS',
  'Hampton, VA',
  'Warren, MI',
  'Charleston, SC',
  'Columbia, SC',
  'Sterling Heights, MI',
  'New Haven, CT',
  'Cedar Rapids, IA',
  'Stamford, CT',
  'Coral Springs, FL',
  'Elizabeth, NJ',
  'Thousand Oaks, CA',
  'Concord, CA',
  'Lafayette, LA',
  'Kent, WA',
  'Topeka, KS',
  'Simi Valley, CA',
  'Santa Clara, CA',
  'Athens, GA',
  'Berkeley, CA',
  'Ann Arbor, MI',
  'Allentown, PA',
  'Abilene, TX',
  'Beaumont, TX',
  'Vallejo, CA',
  'Independence, MO',
  'Round Rock, TX',
  'Provo, UT',
  'Peoria, IL',
  'Norman, OK',
  'Springfield, IL',
  'Wilmington, NC',
  'Asheville, NC',
  'Boulder, CO',
  'Charleston, WV',
  'Burlington, VT',
  'Portland, ME',
  'Manchester, NH',
  'Fargo, ND',
  'Billings, MT',
  'Cheyenne, WY',
  'Wilmington, DE',
  'Sioux City, IA',
  'Green Bay, WI',
  'Palm Springs, CA',
  'Napa, CA',
  'Santa Barbara, CA',
  'Santa Fe, NM',
  'Savannah, TN',
  'Key West, FL',
  'Sarasota, FL',
  'Naples, FL',
  'Myrtle Beach, SC',
  'Gatlinburg, TN',
  'Aspen, CO',
  'Park City, UT',
  'Jackson, WY',
  'Bend, OR',
  'Boca Raton, FL',
  'Scranton, PA',

  // International — major destinations, "City, Country"
  'London, United Kingdom',
  'Paris, France',
  'Rome, Italy',
  'Barcelona, Spain',
  'Madrid, Spain',
  'Amsterdam, Netherlands',
  'Berlin, Germany',
  'Munich, Germany',
  'Vienna, Austria',
  'Prague, Czechia',
  'Budapest, Hungary',
  'Lisbon, Portugal',
  'Porto, Portugal',
  'Dublin, Ireland',
  'Edinburgh, United Kingdom',
  'Copenhagen, Denmark',
  'Stockholm, Sweden',
  'Oslo, Norway',
  'Helsinki, Finland',
  'Reykjavik, Iceland',
  'Zurich, Switzerland',
  'Brussels, Belgium',
  'Athens, Greece',
  'Istanbul, Turkey',
  'Warsaw, Poland',
  'Florence, Italy',
  'Venice, Italy',
  'Milan, Italy',
  'Naples, Italy',
  'Seville, Spain',
  'Valencia, Spain',
  'Nice, France',
  'Lyon, France',
  'Marseille, France',
  'Toronto, Canada',
  'Vancouver, Canada',
  'Montreal, Canada',
  'Quebec City, Canada',
  'Mexico City, Mexico',
  'Cancun, Mexico',
  'Guadalajara, Mexico',
  'Oaxaca, Mexico',
  'Tokyo, Japan',
  'Kyoto, Japan',
  'Osaka, Japan',
  'Seoul, South Korea',
  'Bangkok, Thailand',
  'Chiang Mai, Thailand',
  'Singapore, Singapore',
  'Hong Kong, Hong Kong',
  'Taipei, Taiwan',
  'Ho Chi Minh City, Vietnam',
  'Hanoi, Vietnam',
  'Bali, Indonesia',
  'Kuala Lumpur, Malaysia',
  'Manila, Philippines',
  'Mumbai, India',
  'Delhi, India',
  'Jaipur, India',
  'Dubai, United Arab Emirates',
  'Tel Aviv, Israel',
  'Marrakesh, Morocco',
  'Cairo, Egypt',
  'Cape Town, South Africa',
  'Nairobi, Kenya',
  'Sydney, Australia',
  'Melbourne, Australia',
  'Brisbane, Australia',
  'Auckland, New Zealand',
  'Queenstown, New Zealand',
  'Buenos Aires, Argentina',
  'Rio de Janeiro, Brazil',
  'Sao Paulo, Brazil',
  'Santiago, Chile',
  'Lima, Peru',
  'Cusco, Peru',
  'Bogota, Colombia',
  'Cartagena, Colombia',
  'San Juan, PR',
  'Havana, Cuba',
];

/**
 * The quick-pick chips under the field — a curated subset of the list above,
 * kept here rather than in app/settings.tsx so both sets of values that get
 * written to rooms.locations are covered by the same canonical-form test.
 * cities.test.ts asserts every entry is also in CITY_SUGGESTIONS, so the two
 * cannot drift.
 */
export const POPULAR_METROS: readonly string[] = [
  'New York, NY',
  'Los Angeles, CA',
  'Chicago, IL',
  'San Francisco, CA',
  'Seattle, WA',
  'Austin, TX',
  'Boston, MA',
  'Washington, DC',
  'Miami, FL',
  'Denver, CO',
  'Portland, OR',
  'San Diego, CA',
  'Nashville, TN',
  'New Orleans, LA',
  'Atlanta, GA',
  'Philadelphia, PA',
  'Houston, TX',
  'Dallas, TX',
  'Phoenix, AZ',
  'Las Vegas, NV',
  'Minneapolis, MN',
  'Charleston, SC',
  'San Antonio, TX',
  'Detroit, MI',
  'Honolulu, HI',
];
