-- 008_item_emoji.sql
-- Adds per-item emoji (fixes one category glyph standing in for every item,
-- e.g. a noodle bowl on tacos). Backfills the already-seeded rows by title;
-- fresh seeds get emoji straight from seed.sql.

alter table items add column if not exists emoji text;

update items set emoji = '🍕' where category = 'food' and title = 'Neapolitan pizza';
update items set emoji = '🍣' where category = 'food' and title = 'Sushi night';
update items set emoji = '🌮' where category = 'food' and title = 'Tacos al pastor';
update items set emoji = '🍜' where category = 'food' and title = 'Tonkotsu ramen';
update items set emoji = '🍜' where category = 'food' and title = 'Pad Thai';
update items set emoji = '🍛' where category = 'food' and title = 'Butter chicken';
update items set emoji = '🍔' where category = 'food' and title = 'Smash burgers';
update items set emoji = '🍖' where category = 'food' and title = 'Texas BBQ brisket';
update items set emoji = '🍜' where category = 'food' and title = 'Beef pho';
update items set emoji = '🥟' where category = 'food' and title = 'Pork dumplings';
update items set emoji = '🍗' where category = 'food' and title = 'Korean fried chicken';
update items set emoji = '🍤' where category = 'food' and title = 'Fish and chips';
update items set emoji = '🥙' where category = 'food' and title = 'Falafel wraps';
update items set emoji = '🍝' where category = 'food' and title = 'Spaghetti carbonara';
update items set emoji = '🍝' where category = 'food' and title = 'Baked lasagna';
update items set emoji = '🌯' where category = 'food' and title = 'Burrito bowls';
update items set emoji = '🍤' where category = 'food' and title = 'Poke bowls';
update items set emoji = '🥙' where category = 'food' and title = 'Shakshuka brunch';
update items set emoji = '🥙' where category = 'food' and title = 'Lamb gyros';
update items set emoji = '🍛' where category = 'food' and title = 'Chicken tikka masala';
update items set emoji = '🥟' where category = 'food' and title = 'Dim sum spread';
update items set emoji = '🍲' where category = 'food' and title = 'Bibimbap';
update items set emoji = '🦆' where category = 'food' and title = 'Peking duck';
update items set emoji = '🍤' where category = 'food' and title = 'Seafood paella';
update items set emoji = '🥐' where category = 'food' and title = 'Croissants and coffee';
update items set emoji = '🍗' where category = 'food' and title = 'Chicken and waffles';
update items set emoji = '🌯' where category = 'food' and title = 'Loaded nachos';
update items set emoji = '🥙' where category = 'food' and title = 'Chicken shawarma';
update items set emoji = '🍗' where category = 'food' and title = 'Buffalo wings';
update items set emoji = '🧀' where category = 'food' and title = 'Mac and cheese';
update items set emoji = '🍤' where category = 'food' and title = 'Ceviche';
update items set emoji = '🌯' where category = 'food' and title = 'Beef empanadas';
update items set emoji = '🥖' where category = 'food' and title = 'Banh mi';
update items set emoji = '🍜' where category = 'food' and title = 'Laksa';
update items set emoji = '🍛' where category = 'food' and title = 'Chicken biryani';
update items set emoji = '🥐' where category = 'food' and title = 'Weekend pancakes';
update items set emoji = '🥩' where category = 'food' and title = 'Steak frites';
update items set emoji = '🍝' where category = 'food' and title = 'Gnocchi';
update items set emoji = '🌯' where category = 'food' and title = 'Enchiladas';
update items set emoji = '🍛' where category = 'food' and title = 'Thai green curry';
update items set emoji = '🥟' where category = 'food' and title = 'Pork bao buns';
update items set emoji = '🍨' where category = 'food' and title = 'Gelato run';
update items set emoji = '🍲' where category = 'food' and title = 'Hot pot';
update items set emoji = '🥙' where category = 'food' and title = 'Mezze platter';
update items set emoji = '🥙' where category = 'food' and title = 'Souvlaki plate';
update items set emoji = '🏙️' where category = 'vacations' and title = 'London, England';
update items set emoji = '🏙️' where category = 'vacations' and title = 'Paris, France';
update items set emoji = '🏙️' where category = 'vacations' and title = 'Rome, Italy';
update items set emoji = '🏙️' where category = 'vacations' and title = 'Tokyo, Japan';
update items set emoji = '🏙️' where category = 'vacations' and title = 'Barcelona, Spain';
update items set emoji = '🏙️' where category = 'vacations' and title = 'Lisbon, Portugal';
update items set emoji = '🏙️' where category = 'vacations' and title = 'Amsterdam, Netherlands';
update items set emoji = '🏝️' where category = 'vacations' and title = 'Bali, Indonesia';
update items set emoji = '🏙️' where category = 'vacations' and title = 'Dubai, UAE';
update items set emoji = '🏙️' where category = 'vacations' and title = 'Sicily, Italy';
update items set emoji = '🏙️' where category = 'vacations' and title = 'Kyoto, Japan';
update items set emoji = '🏙️' where category = 'vacations' and title = 'Osaka, Japan';
update items set emoji = '🏙️' where category = 'vacations' and title = 'Marrakech, Morocco';
update items set emoji = '🏙️' where category = 'vacations' and title = 'Istanbul, Turkey';
update items set emoji = '🏝️' where category = 'vacations' and title = 'Santorini, Greece';
update items set emoji = '🏙️' where category = 'vacations' and title = 'Prague, Czech Republic';
update items set emoji = '🏙️' where category = 'vacations' and title = 'Vienna, Austria';
update items set emoji = '🏙️' where category = 'vacations' and title = 'Reykjavik, Iceland';
update items set emoji = '🏔️' where category = 'vacations' and title = 'Queenstown, New Zealand';
update items set emoji = '🏝️' where category = 'vacations' and title = 'Cape Town, South Africa';
update items set emoji = '🏙️' where category = 'vacations' and title = 'Buenos Aires, Argentina';
update items set emoji = '🏝️' where category = 'vacations' and title = 'Rio de Janeiro, Brazil';
update items set emoji = '🏙️' where category = 'vacations' and title = 'Bangkok, Thailand';
update items set emoji = '🏙️' where category = 'vacations' and title = 'Hanoi, Vietnam';
update items set emoji = '🏔️' where category = 'vacations' and title = 'Machu Picchu, Peru';
update items set emoji = '🏔️' where category = 'vacations' and title = 'Banff, Canada';
update items set emoji = '🏙️' where category = 'vacations' and title = 'Mexico City, Mexico';
update items set emoji = '🏝️' where category = 'vacations' and title = 'Tulum, Mexico';
update items set emoji = '🏙️' where category = 'vacations' and title = 'New York City, USA';
update items set emoji = '🏙️' where category = 'vacations' and title = 'New Orleans, Louisiana';
update items set emoji = '🏙️' where category = 'vacations' and title = 'Charleston, South Carolina';
update items set emoji = '🏙️' where category = 'vacations' and title = 'Savannah, Georgia';
update items set emoji = '🏙️' where category = 'vacations' and title = 'San Francisco, California';
update items set emoji = '🏝️' where category = 'vacations' and title = 'Maui, Hawaii';
update items set emoji = '🏔️' where category = 'vacations' and title = 'Sedona, Arizona';
update items set emoji = '🏔️' where category = 'vacations' and title = 'Grand Canyon, Arizona';
update items set emoji = '🏔️' where category = 'vacations' and title = 'Yellowstone, Wyoming';
update items set emoji = '🏔️' where category = 'vacations' and title = 'Yosemite, California';
update items set emoji = '🏔️' where category = 'vacations' and title = 'Aspen, Colorado';
update items set emoji = '🏝️' where category = 'vacations' and title = 'Key West, Florida';
update items set emoji = '🏙️' where category = 'vacations' and title = 'Nashville, Tennessee';
update items set emoji = '🏙️' where category = 'vacations' and title = 'Asheville, North Carolina';
update items set emoji = '🏝️' where category = 'vacations' and title = 'San Diego, California';
update items set emoji = '🏙️' where category = 'vacations' and title = 'Portland, Oregon';
update items set emoji = '🏔️' where category = 'vacations' and title = 'Glacier National Park, Montana';
update items set emoji = '🥾' where category = 'activities' and title = 'Sunrise hike';
update items set emoji = '🎲' where category = 'activities' and title = 'Board game night';
update items set emoji = '🍳' where category = 'activities' and title = 'Cooking class';
update items set emoji = '🔐' where category = 'activities' and title = 'Escape room';
update items set emoji = '🎨' where category = 'activities' and title = 'Pottery class';
update items set emoji = '🧗' where category = 'activities' and title = 'Rock climbing gym';
update items set emoji = '🛶' where category = 'activities' and title = 'Kayaking';
update items set emoji = '🧺' where category = 'activities' and title = 'Farmers market morning';
update items set emoji = '🚴' where category = 'activities' and title = 'Bike ride';
update items set emoji = '⛳' where category = 'activities' and title = 'Mini golf';
update items set emoji = '🎳' where category = 'activities' and title = 'Bowling';
update items set emoji = '🎨' where category = 'activities' and title = 'Paint and sip';
update items set emoji = '🏕️' where category = 'activities' and title = 'Camping trip';
update items set emoji = '🚗' where category = 'activities' and title = 'Weekend road trip';
update items set emoji = '🖼️' where category = 'activities' and title = 'Museum afternoon';
update items set emoji = '🌷' where category = 'activities' and title = 'Botanical garden stroll';
update items set emoji = '🧗' where category = 'activities' and title = 'Bouldering';
update items set emoji = '⛸️' where category = 'activities' and title = 'Ice skating';
update items set emoji = '🧘' where category = 'activities' and title = 'Yoga class';
update items set emoji = '👕' where category = 'activities' and title = 'Thrift store hunt';
update items set emoji = '🏖️' where category = 'activities' and title = 'Beach day';
update items set emoji = '🍎' where category = 'activities' and title = 'Apple picking';
update items set emoji = '🤸' where category = 'activities' and title = 'Trampoline park';
update items set emoji = '🏎️' where category = 'activities' and title = 'Go-kart racing';
update items set emoji = '🛶' where category = 'activities' and title = 'Axe throwing';
update items set emoji = '🧭' where category = 'activities' and title = 'City scavenger hunt';
update items set emoji = '🤝' where category = 'activities' and title = 'Volunteer together';
update items set emoji = '🧘' where category = 'activities' and title = 'Home workout challenge';
update items set emoji = '📷' where category = 'activities' and title = 'Photo walk';
update items set emoji = '🛶' where category = 'activities' and title = 'Stand-up paddleboarding';
update items set emoji = '🎣' where category = 'activities' and title = 'Fishing trip';
update items set emoji = '🐠' where category = 'activities' and title = 'Aquarium visit';
update items set emoji = '🦁' where category = 'activities' and title = 'Zoo day';
update items set emoji = '🪂' where category = 'activities' and title = 'Indoor skydiving';
update items set emoji = '🏎️' where category = 'activities' and title = 'Batting cages';
update items set emoji = '⛳' where category = 'activities' and title = 'Disc golf';
update items set emoji = '🛼' where category = 'activities' and title = 'Rollerblading';
update items set emoji = '🏖️' where category = 'activities' and title = 'Snorkeling';
update items set emoji = '⛸️' where category = 'activities' and title = 'Ski day';
update items set emoji = '🐴' where category = 'activities' and title = 'Horseback riding';
update items set emoji = '🧭' where category = 'activities' and title = 'Geocaching';
update items set emoji = '🎲' where category = 'activities' and title = 'Puzzle marathon';
update items set emoji = '🌷' where category = 'activities' and title = 'Plant a garden';
update items set emoji = '🍺' where category = 'activities' and title = 'Brewery tour';
update items set emoji = '💃' where category = 'activities' and title = 'Dance class';
update items set emoji = '🧺' where category = 'date_nights' and title = 'Sunset picnic';
update items set emoji = '🌅' where category = 'date_nights' and title = 'Stargazing';
update items set emoji = '🍷' where category = 'date_nights' and title = 'Wine tasting';
update items set emoji = '🎤' where category = 'date_nights' and title = 'Karaoke night';
update items set emoji = '🎬' where category = 'date_nights' and title = 'Movie marathon at home';
update items set emoji = '🍽️' where category = 'date_nights' and title = 'Candlelit dinner';
update items set emoji = '🎶' where category = 'date_nights' and title = 'Live music show';
update items set emoji = '🤣' where category = 'date_nights' and title = 'Comedy club';
update items set emoji = '🎬' where category = 'date_nights' and title = 'Drive-in movie';
update items set emoji = '🍸' where category = 'date_nights' and title = 'Rooftop bar';
update items set emoji = '🍳' where category = 'date_nights' and title = 'Cook a new recipe';
update items set emoji = '💆' where category = 'date_nights' and title = 'Home spa night';
update items set emoji = '🏖️' where category = 'date_nights' and title = 'Sunset beach walk';
update items set emoji = '🍦' where category = 'date_nights' and title = 'Ice cream date';
update items set emoji = '📖' where category = 'date_nights' and title = 'Bookstore browse';
update items set emoji = '☕' where category = 'date_nights' and title = 'Coffee shop date';
update items set emoji = '🕹️' where category = 'date_nights' and title = 'Game night for two';
update items set emoji = '🔥' where category = 'date_nights' and title = 'Blanket fort';
update items set emoji = '💆' where category = 'date_nights' and title = 'Couples massage';
update items set emoji = '🍽️' where category = 'date_nights' and title = 'Dinner and a play';
update items set emoji = '🕹️' where category = 'date_nights' and title = 'Arcade night';
update items set emoji = '🍢' where category = 'date_nights' and title = 'Night market food crawl';
update items set emoji = '🌅' where category = 'date_nights' and title = 'Sunrise coffee';
update items set emoji = '💕' where category = 'date_nights' and title = 'Paint night at home';
update items set emoji = '🍷' where category = 'date_nights' and title = 'Fondue night';
update items set emoji = '🍷' where category = 'date_nights' and title = 'Jazz bar';
update items set emoji = '🎶' where category = 'date_nights' and title = 'Dancing out';
update items set emoji = '🕹️' where category = 'date_nights' and title = 'Trivia night';
update items set emoji = '🍽️' where category = 'date_nights' and title = 'Breakfast for dinner';
update items set emoji = '🌅' where category = 'date_nights' and title = 'Watch the sunrise';
update items set emoji = '💕' where category = 'date_nights' and title = 'Late-night diner run';
update items set emoji = '🍷' where category = 'date_nights' and title = 'Cocktails at home';
update items set emoji = '🍽️' where category = 'date_nights' and title = 'Themed dinner night';
update items set emoji = '🍷' where category = 'date_nights' and title = 'Puzzle and wine night';
update items set emoji = '🎡' where category = 'date_nights' and title = 'Ferris wheel ride';
update items set emoji = '👻' where category = 'date_nights' and title = 'Ghost tour';
update items set emoji = '🔥' where category = 'date_nights' and title = 'Fireplace evening';
update items set emoji = '🍢' where category = 'date_nights' and title = 'Food festival';
update items set emoji = '🚣' where category = 'date_nights' and title = 'Rent a rowboat';
update items set emoji = '💕' where category = 'date_nights' and title = 'Sunset drive';
update items set emoji = '🍳' where category = 'date_nights' and title = 'Bake together';
update items set emoji = '🕹️' where category = 'date_nights' and title = 'Photo booth date';
update items set emoji = '💆' where category = 'date_nights' and title = 'At-home pedicures';
update items set emoji = '🎶' where category = 'date_nights' and title = 'Slow dance in the kitchen';
update items set emoji = '📖' where category = 'date_nights' and title = 'Write letters to each other';
update items set emoji = '📺' where category = 'shows' and title = 'Breaking Bad';
update items set emoji = '📺' where category = 'shows' and title = 'The Sopranos';
update items set emoji = '📺' where category = 'shows' and title = 'The Wire';
update items set emoji = '📺' where category = 'shows' and title = 'Game of Thrones';
update items set emoji = '📺' where category = 'shows' and title = 'Stranger Things';
update items set emoji = '📺' where category = 'shows' and title = 'The Office';
update items set emoji = '📺' where category = 'shows' and title = 'Friends';
update items set emoji = '📺' where category = 'shows' and title = 'The Last of Us';
update items set emoji = '📺' where category = 'shows' and title = 'Succession';
update items set emoji = '📺' where category = 'shows' and title = 'Ted Lasso';
update items set emoji = '📺' where category = 'shows' and title = 'The Bear';
update items set emoji = '📺' where category = 'shows' and title = 'Severance';
update items set emoji = '📺' where category = 'shows' and title = 'Better Call Saul';
update items set emoji = '📺' where category = 'shows' and title = 'Chernobyl';
update items set emoji = '📺' where category = 'shows' and title = 'Fleabag';
update items set emoji = '📺' where category = 'shows' and title = 'The Crown';
update items set emoji = '📺' where category = 'shows' and title = 'Wednesday';
update items set emoji = '📺' where category = 'shows' and title = 'The Mandalorian';
update items set emoji = '📺' where category = 'shows' and title = 'House of the Dragon';
update items set emoji = '📺' where category = 'shows' and title = 'Shogun';
update items set emoji = '📺' where category = 'shows' and title = 'True Detective';
update items set emoji = '📺' where category = 'shows' and title = 'Peaky Blinders';
update items set emoji = '📺' where category = 'shows' and title = 'Dark';
update items set emoji = '📺' where category = 'shows' and title = 'Squid Game';
update items set emoji = '📺' where category = 'shows' and title = 'Only Murders in the Building';
update items set emoji = '📺' where category = 'shows' and title = 'Silo';
update items set emoji = '🎬' where category = 'shows' and title = 'The Godfather';
update items set emoji = '🎬' where category = 'shows' and title = 'The Shawshank Redemption';
update items set emoji = '🎬' where category = 'shows' and title = 'Pulp Fiction';
update items set emoji = '🎬' where category = 'shows' and title = 'Inception';
update items set emoji = '🎬' where category = 'shows' and title = 'The Dark Knight';
update items set emoji = '🎬' where category = 'shows' and title = 'Parasite';
update items set emoji = '🎬' where category = 'shows' and title = 'Everything Everywhere All at Once';
update items set emoji = '🎬' where category = 'shows' and title = 'Interstellar';
update items set emoji = '🎬' where category = 'shows' and title = 'Spirited Away';
update items set emoji = '🎬' where category = 'shows' and title = 'Oppenheimer';
update items set emoji = '🎬' where category = 'shows' and title = 'Barbie';
update items set emoji = '🎬' where category = 'shows' and title = 'Dune: Part Two';
update items set emoji = '🎬' where category = 'shows' and title = 'La La Land';
update items set emoji = '🎬' where category = 'shows' and title = 'Get Out';
update items set emoji = '🎬' where category = 'shows' and title = 'Whiplash';
update items set emoji = '🎬' where category = 'shows' and title = 'The Grand Budapest Hotel';
update items set emoji = '🎬' where category = 'shows' and title = 'Spider-Man: Into the Spider-Verse';
update items set emoji = '🎬' where category = 'shows' and title = 'Knives Out';
update items set emoji = '🎬' where category = 'shows' and title = 'Past Lives';
